import { describe, it, expect, beforeEach, afterEach } from "vitest";
import {
  V1_ATLAS_SKUS,
  V1_DEFAULT_SKU,
  resolveDecision,
  resolveDecisionAsync,
  selectDecision,
  selectProviderForScene,
} from "./router.js";

describe("router — V1 Atlas SKU decision", () => {
  it("exposes V1_DEFAULT_SKU = kling-v2-6-pro", () => {
    expect(V1_DEFAULT_SKU).toBe("kling-v2-6-pro");
  });

  it("V1_ATLAS_SKUS does not include kling-v3-pro (policy: single-image buckets exclude v3-pro)", () => {
    expect(V1_ATLAS_SKUS as readonly string[]).not.toContain("kling-v3-pro");
  });

  it("V1_ATLAS_SKUS does not include kling-v2-1-pair (paired-only SKU)", () => {
    expect(V1_ATLAS_SKUS as readonly string[]).not.toContain("kling-v2-1-pair");
  });

  it("resolveDecision returns atlas + V1_DEFAULT_SKU when skuOverride is null/undefined", () => {
    const decision = resolveDecision({
      roomType: "living_room",
      movement: "pan_right",
      skuOverride: null,
    });
    expect(decision.provider).toBe("atlas");
    expect(decision.modelKey).toBe(V1_DEFAULT_SKU);
  });

  it("resolveDecision honors a valid skuOverride", () => {
    const decision = resolveDecision({
      roomType: "kitchen",
      movement: "push_in",
      skuOverride: "kling-v2-master",
    });
    expect(decision.provider).toBe("atlas");
    expect(decision.modelKey).toBe("kling-v2-master");
  });

  it("resolveDecision falls back to V1_DEFAULT_SKU when skuOverride is not in V1_ATLAS_SKUS", () => {
    // Defensive: callers must validate before passing, but the router must not crash on an invalid SKU.
    const decision = resolveDecision({
      roomType: "kitchen",
      movement: "push_in",
      skuOverride: "kling-v3-pro" as unknown as (typeof V1_ATLAS_SKUS)[number],
    });
    expect(decision.provider).toBe("atlas");
    expect(decision.modelKey).toBe(V1_DEFAULT_SKU);
  });
});

describe("router — resolveDecisionAsync", () => {
  const savedFlag = process.env.USE_THOMPSON_ROUTER;

  beforeEach(() => {
    delete process.env.USE_THOMPSON_ROUTER;
  });

  afterEach(() => {
    if (savedFlag !== undefined) {
      process.env.USE_THOMPSON_ROUTER = savedFlag;
    } else {
      delete process.env.USE_THOMPSON_ROUTER;
    }
  });

  it("returns static decision + staticSku when flag is unset (no thompson field)", async () => {
    // USE_THOMPSON_ROUTER is not set — should behave identically to resolveDecision.
    const result = await resolveDecisionAsync({
      roomType: "living_room",
      movement: "push_in",
      skuOverride: null,
    });
    expect(result.decision.provider).toBe("atlas");
    expect(result.decision.modelKey).toBe(V1_DEFAULT_SKU);
    expect(result.staticSku).toBe(V1_DEFAULT_SKU);
    expect(result.thompson).toBeUndefined();
  });

  it("returns static decision + staticSku when flag is 'false'", async () => {
    process.env.USE_THOMPSON_ROUTER = "false";
    const result = await resolveDecisionAsync({
      roomType: "kitchen",
      movement: "orbit",
      skuOverride: "kling-v2-master",
    });
    expect(result.decision.modelKey).toBe("kling-v2-master");
    expect(result.staticSku).toBe("kling-v2-master");
    expect(result.thompson).toBeUndefined();
  });

  it("staticSku is always populated regardless of skuOverride", async () => {
    const result = await resolveDecisionAsync({
      roomType: "master_bedroom",
      movement: null,
      skuOverride: null,
    });
    expect(typeof result.staticSku).toBe("string");
    expect((V1_ATLAS_SKUS as readonly string[]).includes(result.staticSku)).toBe(true);
  });
});

// ─── PRODUCTION ROUTING (Lab parity) ─────────────────────────────────────────
//
// Production pipeline must select the SAME SKU Prompt Lab uses by default
// (Atlas kling-v2-6-pro = V1_DEFAULT_SKU). Native Kling and Runway become
// failover-only. This closes the quality gap between Lab and production
// that surfaced on the 13fe5a96 rerun (2026-05-18): scenes generated by
// native Kling v2 looked visibly worse than the Lab-rendered iterations.

describe("router — production scene routing (Lab parity)", () => {
  it("interior movement routes to Atlas kling-v2-6-pro (Lab default), not native Kling", () => {
    const decision = selectDecision("living_room", "push_in", null);
    expect(decision.provider).toBe("atlas");
    expect(decision.modelKey).toBe(V1_DEFAULT_SKU);
  });

  it("orbit / parallax / dolly interior movements all route to Atlas kling-v2-6-pro", () => {
    for (const movement of ["orbit", "parallax", "dolly_left_to_right", "reveal"] as const) {
      const decision = selectDecision("kitchen", movement, null);
      expect(decision.provider).toBe("atlas");
      expect(decision.modelKey).toBe(V1_DEFAULT_SKU);
    }
  });

  it("drone_push_in routes to Atlas kling-v2-6-pro (Lab parity), not Runway gen4_turbo", () => {
    const decision = selectDecision("exterior_front", "drone_push_in", null);
    expect(decision.provider).toBe("atlas");
    expect(decision.modelKey).toBe(V1_DEFAULT_SKU);
  });

  it("top_down + feature_closeup also route to Atlas kling-v2-6-pro", () => {
    for (const movement of ["top_down", "feature_closeup"] as const) {
      const decision = selectDecision("exterior_front", movement, null);
      expect(decision.provider).toBe("atlas");
      expect(decision.modelKey).toBe(V1_DEFAULT_SKU);
    }
  });

  it("unknown / null movement still defaults to Atlas kling-v2-6-pro", () => {
    const decision = selectDecision("hallway", null, null);
    expect(decision.provider).toBe("atlas");
    expect(decision.modelKey).toBe(V1_DEFAULT_SKU);
  });

  it("drone movement carries Runway as its failover (Runway's historical niche)", () => {
    const decision = selectDecision("exterior_front", "drone_push_in", null);
    expect(decision.fallback?.provider).toBe("runway");
  });

  it("interior movement carries native Kling as its failover (free pre-paid credits)", () => {
    const decision = selectDecision("living_room", "push_in", null);
    expect(decision.fallback?.provider).toBe("kling");
  });

  it("when atlas already failed in this attempt, drone falls back to Runway as primary", () => {
    const decision = selectDecision("exterior_front", "drone_push_in", null, ["atlas"]);
    expect(decision.provider).toBe("runway");
  });

  it("when atlas already failed in this attempt, interior falls back to native Kling as primary", () => {
    const decision = selectDecision("living_room", "push_in", null, ["atlas"]);
    expect(decision.provider).toBe("kling");
  });

  it("explicit scene preference still overrides Lab-parity default", () => {
    // Prompt Lab can pin a specific provider per scene via scene.provider.
    // That preference must still win — otherwise Lab provider picks no-op.
    const decision = selectDecision("kitchen", "push_in", "runway");
    expect(decision.provider).toBe("runway");
  });

  it("paired scene (end_photo_id set) routes to Atlas kling-v3-pro (upgraded from kling-v2-1-pair 2026-06-10)", () => {
    const decision = selectProviderForScene({
      endPhotoId: "photo-end-uuid",
      movement: "push_in",
      roomType: "kitchen",
      preference: null,
    });
    expect(decision.provider).toBe("atlas");
    expect(decision.modelKey).toBe("kling-v3-pro");
  });

  it("paired-scene rule wins even for drone movements", () => {
    const decision = selectProviderForScene({
      endPhotoId: "photo-end-uuid",
      movement: "drone_push_in",
      roomType: "exterior_front",
      preference: null,
    });
    expect(decision.provider).toBe("atlas");
    expect(decision.modelKey).toBe("kling-v3-pro");
  });
});

describe("router — Seedance 4K default (2026-06-30)", () => {
  it("v1.1 mode + video_model_sku=null (Automatic) defaults to seedance-2-0-4k, not seedance-pro-pushin", () => {
    const decision = selectProviderForScene(
      {
        endPhotoId: null,
        movement: "push_in",
        roomType: "kitchen",
        preference: null,
      },
      [],
      "v1.1",
      null,
    );
    expect(decision.provider).toBe("atlas");
    expect(decision.modelKey).toBe("seedance-2-0-4k");
  });

  it("v1.1 default fallback chain degrades 4K -> 1080p Seedance push-in -> V1 default Kling", () => {
    const decision = selectProviderForScene(
      {
        endPhotoId: null,
        movement: "orbit",
        roomType: "living_room",
        preference: null,
      },
      [],
      "v1.1",
      null,
    );
    expect(decision.modelKey).toBe("seedance-2-0-4k");
    expect(decision.fallback?.modelKey).toBe("seedance-pro-pushin");
    expect(decision.fallback?.fallback?.modelKey).toBe(V1_DEFAULT_SKU);
    expect(decision.fallback?.fallback?.fallback).toBeUndefined();
  });

  it("operator SKU override still wins over the 4K default (operator picks 1080p Seedance explicitly)", () => {
    const decision = selectProviderForScene(
      {
        endPhotoId: null,
        movement: "push_in",
        roomType: "bathroom",
        preference: null,
      },
      [],
      "v1.1",
      "seedance-pro-pushin",
    );
    expect(decision.modelKey).toBe("seedance-pro-pushin");
    expect(decision.fallback).toBeUndefined(); // operator override is terminal
  });

  it("operator SKU override still wins over the 4K default (operator picks Kling explicitly)", () => {
    const decision = selectProviderForScene(
      {
        endPhotoId: null,
        movement: "push_in",
        roomType: "bathroom",
        preference: null,
      },
      [],
      "v1.1",
      "kling-v2-master",
    );
    expect(decision.modelKey).toBe("kling-v2-master");
  });

  it("v1 mode (legacy/customer-checkout default) is UNCHANGED — still routes to V1_DEFAULT_SKU (Kling), not 4K", () => {
    const decision = selectProviderForScene(
      {
        endPhotoId: null,
        movement: "orbit",
        roomType: "kitchen",
        preference: null,
      },
      [],
      "v1",
      null,
    );
    expect(decision.provider).toBe("atlas");
    expect(decision.modelKey).toBe(V1_DEFAULT_SKU);
    expect(decision.modelKey).not.toBe("seedance-2-0-4k");
  });

  it("paired scenes (DQ.3) are UNCHANGED under v1.1 mode — still kling-v3-pro (1080p), not 4K", () => {
    const decision = selectProviderForScene(
      {
        endPhotoId: "photo-end-uuid",
        movement: "push_in",
        roomType: "kitchen",
        preference: null,
      },
      [],
      "v1.1",
      null,
    );
    expect(decision.provider).toBe("atlas");
    expect(decision.modelKey).toBe("kling-v3-pro");
  });

  it("atlas excluded mid-failover skips the v1.1 4K branch entirely (no other home for Seedance)", () => {
    const decision = selectProviderForScene(
      {
        endPhotoId: null,
        movement: "push_in",
        roomType: "kitchen",
        preference: null,
      },
      ["atlas"],
      "v1.1",
      null,
    );
    expect(decision.modelKey).not.toBe("seedance-2-0-4k");
  });
});
