import type { ListingSeoArtifactRow } from "./types.js";

export function escapeHtml(value: string): string {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

function escapeJsonForHtml(value: unknown): string {
  return JSON.stringify(value).replace(/</g, "\\u003c");
}

export function renderListingSeoHtml(artifact: ListingSeoArtifactRow, baseUrl: string): string {
  const canonical = `${baseUrl}/listings/${artifact.slug}`;
  const markdownUrl = `${canonical}.md`;
  const graph = artifact.schema_json?.["@graph"] ?? [];
  const video = graph.find((node) => node["@type"] === "VideoObject") as { contentUrl?: string; embedUrl?: string } | undefined;
  const house = graph.find((node) => node["@type"] === "House") as { image?: string[] } | undefined;
  const image = Array.isArray(house?.image) ? house.image[0] : null;
  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>${escapeHtml(artifact.title)}</title>
  <meta name="description" content="${escapeHtml(artifact.meta_description)}" />
  <link rel="canonical" href="${escapeHtml(canonical)}" />
  <meta property="og:type" content="website" />
  <meta property="og:title" content="${escapeHtml(artifact.title)}" />
  <meta property="og:description" content="${escapeHtml(artifact.meta_description)}" />
  ${image ? `<meta property="og:image" content="${escapeHtml(image)}" />` : ""}
  <meta name="twitter:card" content="summary_large_image" />
  <script type="application/ld+json">${escapeJsonForHtml(artifact.schema_json)}</script>
  <style>
    :root { color-scheme: light; font-family: Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; color: #181713; background: #faf9f6; }
    body { margin: 0; }
    main { max-width: 880px; margin: 0 auto; padding: 48px 20px 72px; }
    a { color: #77532b; }
    h1 { margin: 0 0 12px; font-size: clamp(32px, 6vw, 64px); line-height: 0.98; letter-spacing: 0; }
    h2 { margin: 36px 0 12px; font-size: 18px; }
    p, li { font-size: 16px; line-height: 1.7; }
    .meta { color: #706c63; margin: 0 0 28px; }
    .hero { width: 100%; border-radius: 8px; border: 1px solid #dfd8cb; background: #fff; margin: 16px 0 8px; }
    .facts { display: grid; grid-template-columns: repeat(auto-fit, minmax(160px, 1fr)); gap: 10px; padding: 0; list-style: none; }
    .facts li, .qa { border: 1px solid #dfd8cb; border-radius: 8px; background: #fff; padding: 12px 14px; }
    .link-row { display: flex; flex-wrap: wrap; gap: 12px; margin-top: 24px; }
  </style>
</head>
<body>
  <main>
    <h1>${escapeHtml(artifact.title)}</h1>
    <p class="meta">${escapeHtml(artifact.meta_description)}</p>
    ${image ? `<img class="hero" src="${escapeHtml(image)}" alt="${escapeHtml(artifact.title)}" />` : ""}
    <p>${escapeHtml(artifact.long_description)}</p>
    <h2>Highlights</h2>
    <ul class="facts">
      ${artifact.highlights.map((highlight) => `<li>${escapeHtml(highlight)}</li>`).join("\n      ")}
    </ul>
    ${video?.contentUrl ? `<h2>Listing Film</h2><p><a href="${escapeHtml(video.contentUrl)}">Watch the listing film</a></p>` : ""}
    <h2>Questions</h2>
    ${artifact.faqs.map((faq) => `<section class="qa"><h3>${escapeHtml(faq.question)}</h3><p>${escapeHtml(faq.answer)}</p></section>`).join("\n    ")}
    <div class="link-row">
      <a href="${escapeHtml(markdownUrl)}">Markdown for AI agents</a>
      ${video?.embedUrl ? `<a href="${escapeHtml(video.embedUrl)}">Public preview</a>` : ""}
    </div>
  </main>
</body>
</html>`;
}

export function renderSitemapXml(rows: ListingSeoArtifactRow[], baseUrl: string): string {
  const urls = rows.map((row) => {
    const lastmod = row.updated_at ? new Date(row.updated_at).toISOString() : new Date().toISOString();
    return `  <url><loc>${escapeHtml(`${baseUrl}/listings/${row.slug}`)}</loc><lastmod>${lastmod}</lastmod></url>`;
  });
  return `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  <url><loc>${escapeHtml(baseUrl)}</loc></url>
${urls.join("\n")}
</urlset>
`;
}

export function renderLlmsTxt(rows: ListingSeoArtifactRow[], baseUrl: string): string {
  const lines = [
    "# Listing Elevate",
    "",
    "Public, crawlable real estate listing video resources generated by Listing Elevate.",
    "",
    "## Listings",
    ...rows.map((row) => `- [${row.title}](${baseUrl}/listings/${row.slug}.md): ${row.meta_description}`),
    "",
  ];
  return lines.join("\n");
}
