/**
 * director-sequence.ts
 *
 * Pure sequence-manipulation helpers for the DirectorModal timeline.
 * All functions are immutable (return new arrays) and free of side effects.
 *
 * Key contract: keys are NEVER recycled. The caller supplies a `nextKey`
 * string for every add/duplicate — typically generated by a monotonic counter
 * held in a useRef inside the component. This eliminates the original
 * `${iterationId}-${prev.length}` collision bug where removing then re-adding
 * the same clip could produce duplicate keys.
 */

export interface SequenceItem {
  iteration_id: string;
  /** Globally unique key for React / framer-motion identity. */
  key: string;
}

/**
 * Add a new item to the end of the sequence.
 */
export function addItem(
  seq: SequenceItem[],
  iterationId: string,
  nextKey: string,
): SequenceItem[] {
  return [...seq, { iteration_id: iterationId, key: nextKey }];
}

/**
 * Remove the item at position `i`.
 */
export function removeAt(seq: SequenceItem[], i: number): SequenceItem[] {
  if (i < 0 || i >= seq.length) return seq;
  return seq.filter((_, idx) => idx !== i);
}

/**
 * Insert a duplicate of item at position `i` immediately after it.
 * The duplicate gets `nextKey` — never inherits the original's key.
 */
export function duplicateAt(
  seq: SequenceItem[],
  i: number,
  nextKey: string,
): SequenceItem[] {
  const orig = seq[i];
  if (!orig) return seq;
  const dup: SequenceItem = { iteration_id: orig.iteration_id, key: nextKey };
  const next = [...seq];
  next.splice(i + 1, 0, dup);
  return next;
}

/**
 * Move item at index `from` to index `to`.
 * Clamps both indices to [0, seq.length - 1].
 * Returns the original array unchanged when from === to or sequence is
 * empty / single-item.
 */
export function moveItem(
  seq: SequenceItem[],
  from: number,
  to: number,
): SequenceItem[] {
  if (seq.length < 2) return seq;
  const clamp = (n: number) => Math.max(0, Math.min(seq.length - 1, n));
  const f = clamp(from);
  const t = clamp(to);
  if (f === t) return seq;
  const next = [...seq];
  const [item] = next.splice(f, 1);
  next.splice(t, 0, item);
  return next;
}
