-- 068_gen2_pair_candidates.sql
-- Stores deterministically-generated pair candidates per listing.
-- Multiple rows per listing, one per (photo_a, photo_b, candidate_type) tuple.

CREATE TABLE IF NOT EXISTS public.gen2_pair_candidates (
  candidate_id    uuid        NOT NULL DEFAULT gen_random_uuid(),
  listing_id      uuid        NOT NULL,
  photo_a_id      uuid        NOT NULL,
  photo_b_id      uuid        NOT NULL,
  candidate_type  text        NOT NULL,
  heuristic_score numeric,
  reasoning       text,
  portal_id       text,
  created_at      timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT gen2_pair_candidates_pkey PRIMARY KEY (candidate_id),
  CONSTRAINT gen2_pair_candidates_listing_fk
    FOREIGN KEY (listing_id) REFERENCES public.properties(id) ON DELETE CASCADE,
  CONSTRAINT gen2_pair_candidates_photo_a_fk
    FOREIGN KEY (photo_a_id) REFERENCES public.photos(id) ON DELETE CASCADE,
  CONSTRAINT gen2_pair_candidates_photo_b_fk
    FOREIGN KEY (photo_b_id) REFERENCES public.photos(id) ON DELETE CASCADE,
  CONSTRAINT gen2_pair_candidates_type_chk CHECK (
    candidate_type IN (
      'same_room_different_angle',
      'walkthrough_via_portal',
      'wide_to_detail',
      'aerial_to_entry',
      'exterior_walkaround'
    )
  )
);

-- Primary queue query: all candidates for a listing ordered by score
CREATE INDEX IF NOT EXISTS gen2_pair_candidates_listing_score_idx
  ON public.gen2_pair_candidates (listing_id, heuristic_score DESC NULLS LAST);

CREATE INDEX IF NOT EXISTS gen2_pair_candidates_photo_a_idx
  ON public.gen2_pair_candidates (photo_a_id);

CREATE INDEX IF NOT EXISTS gen2_pair_candidates_photo_b_idx
  ON public.gen2_pair_candidates (photo_b_id);

COMMENT ON TABLE public.gen2_pair_candidates IS
  'V2.1 pair candidates generated by rule-generator.ts for a listing. '
  'portal_id is non-null only for walkthrough_via_portal rows.';

NOTIFY pgrst, 'reload schema';
